import type { ModuleSettingsDefinition } from '@org/core';

export const inventorySettingsDefinition: ModuleSettingsDefinition = {
  module: 'inventory',
  label: 'المخزون',
  icon: 'InboxOutlined',
  settings: [
    {
      key: 'valuationMethod',
      label: 'طريقة تقييم المخزون',
      description: 'الطريقة المستخدمة لحساب تكلفة المخزون',
      type: 'select',
      default: 'FIFO',
      group: 'التقييم',
      options: [
        { label: 'FIFO - أول داخل أول خارج', value: 'FIFO' },
        { label: 'AVCO - المتوسط المرجح', value: 'AVCO' },
        { label: 'Standard Cost - التكلفة المعيارية', value: 'STANDARD' },
      ],
    },
    {
      key: 'trackLotNumbers',
      label: 'تتبع أرقام الدفعات',
      description: 'تفعيل تتبع Lot Numbers للمنتجات',
      type: 'boolean',
      default: false,
      group: 'التتبع',
    },
    {
      key: 'trackSerialNumbers',
      label: 'تتبع الأرقام التسلسلية',
      description: 'تفعيل تتبع Serial Numbers للمنتجات',
      type: 'boolean',
      default: false,
      group: 'التتبع',
    },
    {
      key: 'allowNegativeStock',
      label: 'السماح بمخزون سالب',
      description: 'السماح بتسجيل مبيعات حتى لو المخزون صفر',
      type: 'boolean',
      default: false,
      group: 'القواعد',
    },
    {
      key: 'requireTransferApproval',
      label: 'موافقة على التحويل',
      description: 'يتطلب موافقة مدير قبل تحويل المخزون',
      type: 'boolean',
      default: false,
      group: 'الموافقات',
    },
    {
      key: 'requireAdjustmentApproval',
      label: 'موافقة على التسوية',
      description: 'يتطلب موافقة مدير قبل تأكيد الجرد',
      type: 'boolean',
      default: false,
      group: 'الموافقات',
    },
    {
      key: 'enableLowStockAlert',
      label: 'تنبيه نقص المخزون',
      description: 'إرسال تنبيه عند وصول المخزون للحد الأدنى',
      type: 'boolean',
      default: true,
      group: 'التنبيهات',
    },
    {
      key: 'defaultMinStock',
      label: 'الحد الأدنى الافتراضي',
      description: 'الكمية الافتراضية للحد الأدنى للمخزون',
      type: 'number',
      default: 0,
      min: 0,
      group: 'التنبيهات',
    },
  ],
};