export { inventoryRoutes } from './lib/routes';
export { inventoryApi } from './lib/api/inventory.api';
export { default as ProductsPage } from './lib/pages/products.page';
export { default as WarehousesPage } from './lib/pages/warehouses.page';
export { default as StockPage } from './lib/pages/stock.page';
export { default as StockMovementsPage } from './lib/pages/stock-movements.page';
export { default as AdjustmentsPage } from './lib/pages/adjustments.page';
export { default as ReorderingRulesPage } from './lib/pages/reordering-rules.page';
export { default as CategoriesPage } from './lib/pages/categories.page';
export { default as UnitsPage } from './lib/pages/units.page';
export { default as InventorySettingsPage } from './lib/pages/settings.page';
export { default as ProductDetailPage } from './lib/pages/product-detail.page';
export { default as TraceabilityPage } from './lib/pages/traceability.page';
export { default as StockValuationPage } from './lib/pages/stock-valuation.page';
export { useProducts } from './lib/hooks/useProducts';